AdditionalRoom.create!([
{ options: 'Atrium' },
{ options: 'Attic' },
{ options: 'Cottage' },
{ options: 'Den/Library/Office' },
{ options: 'Family Room' },
{ options: 'Florida Room' },
{ options: 'Foyer' },
{ options: 'Game Room' },
{ options: 'Garage Apartment' },
{ options: 'Garage Converted' },
{ options: 'Glassed Porch' },
{ options: 'Great Room' },
{ options: 'Separate Guest/In-Law Quarters' },
{ options: 'Guest House' },
{ options: 'Laundry' },
{ options: 'Loft' },
{ options: "Maid's Quarters" },
{ options: 'Maid/In-Law Quarters' },
{ options: 'Media Room' },
{ options: 'No Additional Rooms' },
{ options: 'Other' },
{ options: 'Pantry' },
{ options: 'Recreation Room' },
{ options: 'Sauna' },
{ options: 'Screened Patio/Porch' },
{ options: 'Storage Room' },
{ options: 'Studio Apartment' },
{ options: 'Utility/Laundry In Garage' },
{ options: 'Utility Room/Laundry' },
{ options: 'Utility Room' },
{ options: 'Workshop' }])

p "Created #{AdditionalRoom.count} AdditionalRoom options"
