Amenity.destroy_all
Amenity.create!([
{ options: 'Activity Room' },
{ options: 'Bar' },
{ options: 'Card/Electric Gate' },
{ options: 'Country Club Membership' },
{ options: 'Club Membership Required' },
{ options: 'Clubhouse' },
{ options: 'Community Pool' },
{ options: 'Elevator' },
{ options: 'Exercise Room' },
{ options: 'Golf Equity Available' },
{ options: 'Golf Equity Included' },
{ options: 'Golf' },
{ options: 'Guard At Gate' },
{ options: 'Handball/Basketball' },
{ options: 'Kitchen Facilities' },
{ options: 'Laundry Facility' },
{ options: 'Maintained Community' },
{ options: 'Management On Site' },
{ options: 'Other Amenities' },
{ options: 'Other Membership Available' },
{ options: 'Other Membership Included' },
{ options: 'Child Play Area' },
{ options: 'Pool Table' },
{ options: 'Putting Green' },
{ options: 'Sauna' },
{ options: 'Security Patrol' },
{ options: 'Spa/Hot Tub' }])

p "Created #{Amenity.count} Amenity options"
