Equipment.destroy_all
Equipment.create!([
{ options: 'Automatic Garage Door Opener' },
{ options: 'Bottled Gas' },
{ options: 'Central Vacuum' },
{ options: 'Trash Compactor' },
{ options: 'Dishwasher' },
{ options: 'Disposal' },
{ options: 'Dryer' },
{ options: 'Electric Water Heater' },
{ options: 'Elevator' },
{ options: 'Fire Alarm' },
{ options: 'Separate Freezer Included' },
{ options: 'Gas Tank Leased' },
{ options: 'Gas Water Heater' },
{ options: 'Washer/Dryer Hook-Up' },
{ options: 'Water Heater Leased' },
{ options: 'Icemaker' },
{ options: 'Intercom' },
{ options: 'Microwave' },
{ options: 'Natural Gas' },
{ options: 'No Equipment' },
{ options: 'Other Equipment/Appliances' },
{ options: 'Owned Burglar Alarm' },
{ options: 'Purifier/Sink' },
{ options: 'Electric Range' },
{ options: 'Gas Range' },
{ options: 'Refrigerator' },
{ options: 'Security System Leased' },
{ options: 'Self Cleaning Oven' },
{ options: 'Smoke Detector' },
{ options: 'Solar Water Heater' },
{ options: 'Washer/Dryer Leased' },
{ options: 'Wall Oven' },
{ options: 'Washer' },
{ options: 'Water Softener/Filter Owned' },
{ options: 'Water Softener/Filter Rented' }])
p "created #{Equipment.count} Equipment options"