ExteriorFeature.create!([
{ options: 'Awnings' },
{ options: 'Barbeque' },
{ options: 'Barn &/Or Stalls' },
{ options: 'Built-In Grill' },
{ options: 'Deck' },
{ options: 'Extra Building/Shed' },
{ options: 'Fence' },
{ options: 'Fruit Trees' },
{ options: 'Greenhouse' },
{ options: 'High Impact Doors' },
{ options: 'Exterior Lighting' },
{ options: 'None' },
{ options: 'Open Balcony' },
{ options: 'Open Porch' },
{ options: 'Other' },
{ options: 'Outdoor Shower' },
{ options: 'Patio' },
{ options: 'Room For Pool' },
{ options: 'Satellite Dish' },
{ options: 'Screened Balcony' },
{ options: 'Screened Porch' },
{ options: 'Shed' },
{ options: 'Electric Shutters' },
{ options: 'Storm/Security Shutters' },
{ options: 'Tennis Court' },
{ options: 'Tv Antenna' },
{ options: 'Wraparound Porch' }])
p "Created #{ExteriorFeature.count} ExteriorFeature options"