InteriorFeature.create!([
{ options: 'First Floor Entry' },
{ options: 'Second Floor Entry' },
{ options: 'Third Floor Entry' },
{ options: 'Bar' },
{ options: 'Built-Ins' },
{ options: 'Closet Cabinetry' },
{ options: 'Cooking Island' },
{ options: 'Custom Mirrors' },
{ options: 'Dome Kitchen' },
{ options: 'Elevator' },
{ options: 'Exclusions' },
{ options: 'Fireplace' },
{ options: 'Fire Sprinklers' },
{ options: 'Foyer Entry' },
{ options: 'Fireplace-Decorative' },
{ options: 'French Doors' },
{ options: 'Handicap Accessible' },
{ options: 'Handicap Equipped' },
{ options: 'Laundry Tub' },
{ options: 'Other Interior Features' },
{ options: 'Pantry' },
{ options: 'Pull Down Stairs' },
{ options: 'Chandelier To Be Replaced' },
{ options: 'Roman Tub' },
{ options: 'Skylight' },
{ options: 'Split Bedroom' },
{ options: 'Stacked Bedroom' },
{ options: '3 Bedroom Split' },
{ options: 'Vaulted Ceilings' },
{ options: 'Volume Ceilings' },
{ options: 'Walk-In Closets' },
{ options: 'Certified Watt-Wise' },
{ options: 'Wet Bar' }])
p "Created #{InteriorFeature.count} InteriorFeature options"
