# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3992a383f0b6c32f639e245e2f405203596ef9cfd1ecf32b971ac82b07f64892fdc05fe5e3da7829400216fefe0e403fb96a0efdac5471438391d4088c09a851
  aws_bucket_name: "leasedup"
  aws_access_key: "AKIAJNTYOO5DWABXY4VQ"
  aws_secret_key: "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"

test:
  secret_key_base: 43ebde2cd7cc74d14efda09e5020c972c01df5f40befbcdd00e5257bd7c03e6f4ec12e4fddb75f323b02e8be3c615a7bd1de14d82dc369a013c4301d8184b0e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>